const CHEATSHEET_DATA = {
  fr: [
    {
      category: "AWS Solutions Architect Associate - Certification",
      memos: [
        {
          title: "Calcul, Conteneurs & Serverless (Subtilités)",
          tags: ["Compute", "Containers", "Serverless"],
          search: "lambda snapstart ecs eks ecr fargate unmanaged managed",
          markdown: "**Unmanaged vs Managed vs Serverless :**\n- *Unmanaged* : AWS s'occupe du physique. Tu gères OS, patchs sécu, config (Ex: EC2).\n- *Managed* : AWS gère infrastructure, OS, backups, updates. Tu gères uniquement la config du service et les données (Ex: RDS).\n- *Serverless* : Tu envoies juste le code. Scaling automatique, pas de serveur à gérer, facturation à l'usage réel (Ex: Lambda).\n\n**Lambda :** Exécution sur événement. Facturation à la milliseconde.\n- *Tricky* : Une fonction ne peut pas durer plus de 15 min.\n- *Tricky* : **Lambda SnapStart** réduit le cold start via une snapshot de l'environnement (surtout pratique pour Java).\n\n**ECS vs EKS :** Orchestrateurs de conteneurs Docker à grande échelle. ECS est propre à AWS et simple. EKS est basé sur Kubernetes (open-source), idéal pour rester compatible multi-cloud.\n\n**ECR :** Le \"parking\" / \"garde-manger\" pour stocker et déployer les images Docker de manière sécurisée.\n\n**Moteurs de calcul (Launch types) :**\n- *Avec EC2* : Contrôle total des serveurs (OS, type de machine) -> Unmanaged/Managed.\n- *Avec Fargate* : Zéro serveur à administrer, moteur serverless, tu définis juste CPU/RAM.\n\n**Résumé flash :** ECS/EKS = Chef d'orchestre | ECR = Parking | EC2/Fargate = Moteur.",
          lang: "text",
          code: "Lambda Max = 15min\nJava Cold Start -> SnapStart\nECS/EKS (Orchestrateur) -> ECR (Parking) -> EC2/Fargate (Moteur)"
        },
        {
          title: "Réseau VPC, Routage & Connectivité Privée",
          tags: ["Network", "VPC", "Routing"],
          search: "nacl security group endpoint privatelink global accelerator direct connect vpn",
          markdown: "**Règles d'or des sous-réseaux :**\n- *Tricky* : Un subnet c'est **forcément** une seule AZ.\n- *Tricky* : **VPC Sharing** = Partager des subnets dans le VPC, pas le VPC entier.\n\n**NACL vs Security Group :**\n- *Security Group* : Pare-feu niveau instance (EC2). **Stateful** (se souvient du trafic, la réponse sort auto). Ne fait que du **Allow** (bloque tout par défaut).\n- *NACL* : Pare-feu niveau sous-réseau (un NACL par subnet). **Stateless** (les règles doivent être vérifiées à l'aller ET au retour dans les 2 sens). Idéal pour du **Deny** massif (bloquer une IP malveillante spécifique).\n\n**VPC Endpoints :**\n- *Tricky* : Les Gateway Endpoints n'existent **que** pour **S3** et **DynamoDB**.\n- *Tricky* : Pour tous les autres services (comme EFS), on utilise obligatoirement des **Interface Endpoints (AWS PrivateLink)**.\n\n**Passerelles Externes :**\n- *Internet Gateway (IGW)* : Porte d'entrée publique indispensable pour le trafic bidirectionnel avec Internet (sites web publics).\n- *NAT Gateway* : Passerelle à sens unique. Permet aux instances privées (BDD) d'aller sur Internet (mises à jour) tout en restant masquées/invisibles derrière une autre IP de l'extérieur.\n- *Transit Gateway* : Hub central (routeur) pour interconnecter VPC et réseaux on-premises sans faire de fouillis.\n\n**Routage de trafic avancé :**\n- *Tricky* : **Global Accelerator** = Pour le trafic **non-HTTP** (ex: UDP ou MQTT). Permet aussi le déploiement Blue/Green.\n- *Tricky* : **CloudFront** = Pour le trafic **HTTP** (stocke dans les edge locations).\n- *Tricky* : CloudFront ne pointe **jamais** vers un DNS Route 53 (sinon boucle infinie).\n- *Tricky* : Le certificat SSL pour CloudFront doit **obligatoirement** être demandé dans **us-east-1**.\n- *Tricky* : Pour les endpoints régionaux (ALB, API Gateway), les certificats SSL doivent être demandés dans la région concernée.\n\n**Aide-mémoire Examen Connectivité :**\n- Individus vers AWS → Client VPN (élastique, managed, serverless).\n- Bureaux vers AWS via Internet → Site-to-Site VPN (tunnel IPsec chiffré, rapide, économique, bon backup si Direct Connect plante).\n- Service vers VPC sans Internet → PrivateLink.\n- Performance garantie / gros transferts de data → Direct Connect (ligne fibre optique privée dédiée, contourne Internet, rapide, sans embouteillages).",
          lang: "text",
          code: "1 Subnet = 1 AZ (Strict)\nSecurity Group = Stateful + Allow seulement\nNACL = Stateless + Gère le Deny\nS3/DynamoDB = Gateway Endpoint | Autres = Interface Endpoint\nCloudFront Certificat = us-east-1 indispensable"
        },
        {
          title: "Stockage (EBS, Instance Store, S3, EFS, FSx, Gateways)",
          tags: ["Storage"],
          search: "ebs instance store s3 efs fsx storage gateway file volume tape dlm s3ta",
          markdown: "**Stockage Bloc EC2 :**\n- *EC2 Instance Store* : Stockage local du serveur. Non persistant (si tu l'éteins, tu perds tout).\n- *Amazon EBS* : Disque dur virtuel persistant (bloc, type SSD pour OS/BDD) lié à une instance. Doit être dans la même AZ pour y accéder.\n- *Tricky* : Pendant qu'EBS fait une snapshot, tu peux continuer à utiliser le disque normalement, il ne s'arrête pas. Géré via **Amazon DLM** pour automatiser la création/durée de rétention.\n- *Tricky* : Pour avoir du **High I/O**, il faut en priorité un bon disque de stockage.\n\n**Amazon S3 (Stockage Objet) :** Fichiers rangés dans des buckets uniques au monde, privé par défaut (géré via Bucket Policies).\n- *S3 Lifecycle* : Déplacement auto via *Transition actions* (ex: vers Glacier après 90 jours) ou suppression via *Expiration actions* (ex: logs d'un an).\n- *Tricky* : **S3TA (Transfer Acceleration)** = Accélère uniquement le trajet entre un client (PC, mobile, serveur local) et un bucket via les Edge Locations. Pas de transfert bucket à bucket.\n\n**Stockage Partagé (EFS vs FSx) :**\n- *Amazon EFS* : Système de fichiers partagé (protocole NFS) pour instances EC2. Élastique et accessible depuis **plusieurs AZ** en même temps.\n- *Amazon FSx* : Stockage géré multi-protocoles très haute performance (HPC, machine learning). Supporte Windows (SMB), Lustre, NetApp ONTAP, OpenZFS.\n\n**AWS Storage Gateway (Hybride local/cloud) :**\n- *S3 File Gateway* : Fait apparaître les buckets S3 comme des dossiers partagés locaux (NFS/SMB).\n- *Volume Gateway* : Présente le stockage cloud comme des disques durs virtuels locaux via protocole **iSCSI**. Stocké sous forme de snapshots EBS.\n  - *Cached Mode* : Données complètes sur AWS, seuls les fichiers récents sont en cache local pour la vitesse.\n  - *Stored Mode* : Données stockées intégralement en local, sauvegardes automatiques vers AWS.\n- *Tape Gateway* : Remplace les infrastructures de bandes magnétiques physiques par des bandes virtuelles sur S3 Glacier.",
          lang: "text",
          code: "Instance Store = Éphémère (Perte si arrêt) | EBS = Snapshot sans arrêt\nEFS = NFS Linux Multi-AZ | FSx = SMB Windows & Lustre HPC\nVolume Gateway = Protocole iSCSI\nS3TA = Client -> Bucket (Pas bucket -> bucket)"
        },
        {
          title: "Bases de Données (RDS, Aurora, DynamoDB, ElastiCache, Outils)",
          tags: ["Database", "Cache"],
          search: "rds aurora dynamodb elasticache redis memcached documentdb neptune backup",
          markdown: "**Bases Relationnelles (SQL) :**\n- *Amazon RDS* : SQL géré (MySQL, Postgres, Oracle). Utilisez le **Multi-AZ** pour la haute disponibilité (survie en cas de panne) et les **Read Replicas** pour booster les performances de lecture.\n- *Amazon Aurora* : Version premium cloud-native de RDS (jusqu'à 5x plus rapide). Réplique les données 6 fois sur 3 AZ différentes. Utilise *Aurora Autoscaling* pour ajuster dynamiquement les performances des read replicas.\n\n**Bases NoSQL & Spécialisées :**\n- *Amazon DynamoDB* : NoSQL clé-valeur serverless, performances constantes (latence en millisecondes), schéma flexible.\n  - *Tricky* : **L'autoscaling de DynamoDB n'est pas activé par défaut**.\n- *Amazon DocumentDB* : Base documentaire gérée pour données semi-structurées (fichiers JSON).\n  - *Tricky* : Retenir sa compatibilité absolue avec **MongoDB**.\n- *Amazon Neptune* : Base de données de type **Graph** pour analyser les relations complexes (réseaux sociaux, moteurs de recommandation, détection de fraude).\n\n**Mise en cache (Amazon ElastiCache) :** Infos stockées en RAM pour répondre en moins d'une milliseconde.\n- *Tricky* : **Tout le temps Redis** par défaut (réplication, haute disponibilité).\n- *Tricky* : Choisir **Memcached** uniquement si l'architecture requiert du **multi-thread**.\n\n**Sauvegarde & Migration :**\n- *AWS Backup* : Centralise et automatise les stratégies de sauvegarde sur tout AWS (EBS, EFS, RDS) au lieu de configurer séparément.\n- *AWS DMS (Database Migration Service)* : Migration sécurisée. La BDD source reste **totalement opérationnelle** pendant le transfert (downtime minimal). Peut continuer à synchroniser en continu.\n  - *Tricky* : On peut utiliser DMS pour pousser des données de S3 vers Kinesis Data Streams.",
          lang: "text",
          code: "DynamoDB Autoscaling = OFF par défaut\nMongoDB = DocumentDB | Graph = Neptune\nCache standard = Redis | Cache Multi-thread = Memcached\nDMS = BDD source active pendant migration"
        },
        {
          title: "Data Analytics, ETL & Processus Data",
          tags: ["Analytics", "Data"],
          search: "etl kinesis streams firehose glue redshift spectrum emr athena quicksight",
          markdown: "**Le processus ETL :** Extract (récupère de sources variées), Transform (nettoie/formate), Load (envoie vers la destination comme un entrepôt).\n\n**Collecte et Flux de données :**\n- *Amazon Kinesis Data Streams* : Capture et collecte de données en streaming en temps réel à très grande échelle (logs, capteurs IoT).\n- *Amazon Data Firehose* : Charge les flux en \"presque\" temps réel (quelques secondes de délai) directement vers S3 ou Redshift avec mise à l'échelle automatique.\n\n**Stockage et Entrepôts :**\n- *Amazon S3 (Data Lake) :* Point de départ de tout pipeline, stocke tout du brut au non-structuré.\n- *Amazon Redshift :* Data Warehouse haute performance optimisé pour les analyses complexes sur des pétaoctets de données structurées.\n  - *Tricky* : **Redshift Spectrum** = Permet de requêter directement les données de S3 depuis Redshift sans aucun chargement préalable.\n- *AWS Glue :* Service ETL géré qui prépare et nettoie les données. Inclut un *Data Catalog* (index/inventaire de toutes tes sources).\n- *Amazon EMR :* Le \"poids lourd\" du Big Data, utilise des frameworks comme Apache Spark ou Hadoop sur des volumes gigantesques via des clusters de serveurs.\n\n**Requêtage & Visualisation :**\n- *Amazon Athena :* Service de requêtes Serverless pour analyser les données de S3 en utilisant simplement du **SQL**, sans rien installer (facturation uniquement à la requête).\n- *Amazon QuickSight :* Outil de visualisation pour créer des tableaux de bord interactifs (dashboards).\n- *Amazon OpenSearch Service :* Recherche et surveillance de logs textuels en temps réel pour trouver des erreurs ou incidents de sécurité.",
          lang: "text",
          code: "Redshift Spectrum = Requêtes Redshift -> S3 sans import\nAthena = Requêtes SQL directes sur S3 (Serverless)\nEMR = Big Data massifs (Spark/Hadoop)"
        },
        {
          title: "Gestion des Accès IAM & Sécurité des Identités",
          tags: ["Security", "IAM"],
          search: "iam user group role policy deny boundary identity center secrets manager systems manager",
          markdown: "**Principes de base de l'IAM :** Compétence n°1 de l'Ingénieur Sécurité. Par défaut, tout est interdit (**Implicit Deny**). Principe du moindre privilège.\n- *Tricky* : Pour les IAM Policies, **s'il y a un Deny, alors c'est Deny** (l'emporte sur n'importe quel Allow).\n- *Tricky* : On ne peut **pas** attacher une *permission boundary* à un groupe.\n- *Tricky* : L'IAM est global, donc on peut utiliser le même rôle pour plusieurs régions.\n\n**Composants clés :**\n- *IAM User* : Une personne ou application au sein de l'organisation avec son propre identifiant/mot de passe.\n- *IAM Group* : Ensemble d'utilisateurs qui héritent des permissions du groupe (facilite la gestion).\n- *IAM Role* : Identité pour accorder un accès temporaire sans mot de passe.\n  - *Tricky* : Le rôle est dédié à ceux qui n'ont **pas de compte utilisateur permanent** (les services AWS comme EC2, les utilisateurs de l'entreprise via Active Directory, ou les utilisateurs d'autres comptes AWS).\n- *IAM Policy* : Document JSON définissant précisément les autorisations/interdictions attaché à un utilisateur, groupe ou rôle.\n\n**Gestion centralisée et secrets :**\n- *AWS IAM Identity Center (ex-SSO)* : Centralise la connexion à plusieurs comptes AWS et applications avec un seul identifiant (Federated Identity) dans les grandes entreprises.\n- *AWS Secrets Manager* : Stocke et fait pivoter (*rotate*) automatiquement les mots de passe de BDD, clés API et secrets pour éviter de les laisser \"en dur\" dans le code.\n- *AWS Systems Manager* : Gestion à distance centralisée des serveurs (nodes) pour patcher la sécurité de centaines de machines en un clic ou gérant les configs sans connexion manuelle.",
          lang: "json",
          code: "{\n  \"Effect\": \"Deny\",\n  \"Action\": \"*\",\n  \"Resource\": \"*\"\n}"
        },
        {
          title: "Protection, Détection & Audits de Sécurité",
          tags: ["Security", "SecOps", "Audit"],
          search: "shield waf kms macie acm inspector guardduty detective security hub artifact config audit manager",
          markdown: "**Protection active :**\n- *AWS Shield* : Protection contre les attaques DDoS. Version Standard gratuite et automatique. Version Advanced payante contre les attaques sophistiquées avec accès aux experts 24/7.\n- *AWS WAF (Web Application Firewall)* : Pare-feu applicatif filtrant le trafic HTTP/HTTPS entrant contre l'injection SQL ou le XSS via des listes Web ACL.\n- *AWS KMS* : Service centralisé de création et gestion des clés de chiffrement (les clés ne quittent jamais le service, contrôlé via IAM).\n\n**Détection, Analyse & Conformité :**\n- *Amazon Inspector* : Analyse automatique des vulnérabilités logicielles (**CVE**) et erreurs de configuration sur EC2, conteneurs et fonctions Lambda.\n- *Amazon GuardDuty* : Détection intelligente des menaces qui inspecte les logs et surveille l'activité réseau via le machine learning (ex: minage crypto).\n- *Amazon Detective* : Outil d'investigation après une attack pour remonter à la cause profonde (*root cause*) via des visualisations interactives.\n- *AWS Security Hub* : Tableau de bord centralisé de la sécurité qui agrège les alertes (GuardDuty, Inspector, Macie) et montre le niveau de conformité global.\n- *Amazon Macie* : Utilise l'IA pour découvrir et protéger les données sensibles (cartes bancaires, passeports) stockées dans Amazon S3.\n\n**Gouvernance & Audit de l'infrastructure :**\n- *AWS CloudTrail* : Traçabilité et audit. Enregistre chaque action effectuée sur le compte (qui a fait quoi, quand, depuis quelle IP) sous forme d'historique d'appels API.\n- *AWS Config* : Surveille les configurations des ressources, enregistre l'historique des changements et vérifie la conformité par rapport à tes règles de sécurité (peut corriger automatiquement).\n- *AWS Artifact* : Portail gratuit pour télécharger les rapports officiels de conformité d'AWS (ISO, PCI, SOC) et gérant les accords juridiques (BAA pour les données de santé).\n- *AWS Audit Manager* : Aide à préparer les audits en collectant automatiquement des preuves de l'utilisation d'AWS par rapport aux standards de l'industrie (RGPD, PCI DSS).",
          lang: "text",
          code: "CloudTrail = Actions API (Qui a fait quoi?) | AWS Config = Conformité des configurations\nInspector = Détection des CVE | GuardDuty = Surveillance intelligente des logs"
        },
        {
          title: "Gouvernance Multi-Comptes, Évaluations & Déploiement",
          tags: ["Governance", "Deployment", "Migration"],
          search: "organizations scp control tower service catalog cloudformation beanstalk mgn sct",
          markdown: "**Gestion multi-comptes d'entreprise :**\n- *AWS Organizations* : Gestion centrale pour regrouper et gérer plusieurs comptes AWS par unités organisationnelles (OU) avec facturation consolidée (*Consolidated Billing*) pour bénéficier de remises sur volume.\n- *Service Control Policies (SCP)* : Fixent les limites maximales de permissions pour tous les comptes d'une organisation ou d'une OU (peut interdire des régions ou la suppression de logs, même aux admins).\n- *AWS Control Tower* : Met en place un environnement multi-comptes sécurisé (*Landing Zone*) en quelques clics et applique des règles de sécurité obligatoires (*Guardrails*) comme l'activation du MFA ou de CloudTrail.\n\n**Déploiement & Catalogues :**\n- *CloudFormation* : Infrastructure as Code (IaC). Fichier template (YAML ou JSON) décrivant les ressources pour les créer automatiquement dans un ensemble appelé \"Stack\" (infrastructure répétable sans erreur humaine).\n- *Elastic Beanstalk* : Déploiement simplifié au maximum d'applications web. Tu uploades le code (Java, Python, Node.js) et AWS gère automatiquement le provisionnement, l'ELB, l'auto-scaling et le monitoring.\n- *AWS Service Catalog* : Catalogue de modèles de ressources pré-approuvées (ex: \"Serveur Web Sécurisé Standard\") par l'équipe informatique pour les développeurs.\n\n**Outils Techniques de Migration :**\n- *AWS MGN (Application Migration Service)* : Le \"camion de déménagement\" principal pour déplacer et moderniser automatiquement des serveurs physiques/virtuels vers AWS sans interruption utilisateur.\n- *AWS SCT (Schema Conversion Tool)* : Indispensable en migration hétérogène (changement de moteur de BDD, ex: Oracle vers Postgres) pour traduire automatiquement le schéma et le code interne.\n- *AWS Snowball Edge Storage Optimized* : Valise physique blindée contenant des disques pour copier des téraoctets de données localement et les envoyer par transporteur vers S3 (évite de saturer le réseau pendant des mois).\n- *Stratégie Disaster Recovery (Pilot Light)* : Tout est en place (y compris les bases de données répliquées), mais les serveurs de calcul restent éteints pour économiser de l'argent (démarrés uniquement en cas de sinistre).",
          lang: "text",
          code: "Organizations -> Regroupement comptes + Consolidated Billing\nSCP = Limites max de permissions (Même pour l'admin)\nCloudFormation = IaC (Templates JSON/YAML)\nPilot Light = BDD active + Serveurs éteints"
        }
      ]
    },
    {
      category: "[LeetCode] 54. Spiral Matrix - Solution and Explanation (Python)",
      memos: [
        {
          title: "54. Spiral Matrix (Approche Récursive Destructive)",
          tags: ["Array", "Matrix", "Simulation", "Recursion"],
          search: "spiral matrix recursion pop simulation multi-dimensional array slice",
          markdown: "**Le Problème :**\nParcourir une matrice M x N en spirale (sens des aiguilles d'une montre) et stocker les éléments dans un tableau linéaire.\n\n![Problème LeetCode 54](images/leetcode-54-spiral-matrix.png)\n\n**1. La Logique : Réduction par Destruction**\nL'approche consiste à peler la matrice couche par couche. Chaque direction valide un morceau du parcours, puis ampute physiquement la matrice pour réduire la taille du problème :\n\n![Schéma 1 : Le concept du pelage d'oignon](images/leetcode-54-spiral-matrix-1.png)\n\n- **Mouvement Droite (Right) :**\nOn extrait toute la première ligne (index 0). On supprime cette ligne via `matrix.pop(0)`. On passe au flanc droit en mode 'bottom'.\n\n- **Mouvement Bas (Bottom) :**\nOn extrait le dernier élément de chaque ligne (index -1). On nettoie chaque fin de ligne via `matrix[i].pop(-1)`. On passe à la base en mode 'left'.\n\n- **Mouvement Gauche (Left) :**\nOn extrait la dernière ligne restante de droite à gauche (index -1). On supprime cette ligne complète via `matrix.pop(-1)`. On passe au flanc gauche en mode 'top'.\n\n- **Mouvement Haut (Top) :**\nOn remonte du bas vers le haut (range inversé). On extrait le premier élément de chaque ligne (index 0). On nettoie chaque début de ligne via `matrix[i].pop(0)`. On boucle en repassant en mode 'right'.\n\n**2. Le Cas Limite : Piège des Listes Vides**\nSur des formats asymétriques comme **[[7],[9],[6]]**, vider les colonnes ne détruit pas les tableaux parents. Après l'étape 'bottom', la matrice d'origine ne devient pas **[]**. Elle conserve des résidus de structures vides : **[[], []]**.\n\nUn test classique **if matrix == []** échoue donc et provoque une erreur d'index au tour suivant. La barrière de sécurité absolue pour stopper la récursion est :\n**if not matrix or not matrix[0]**\n\n**3. Analyse de Performance**\n- **Complexité Espace : O(min(M, N))**\nDéterminée par la taille de la pile d'appels (call stack) liée à la récursion profonde de la spirale.\n\n- **Complexité Temps : O((M x N) x max(M, N))**",
          lang: "python",
          code: "class Solution(object):\n    def spiralOrder(self, matrix):\n        dir = \"right\"\n        result = []\n\n        def matrix_parcour(dir, matrix):\n            if not matrix or not matrix[0]:\n                return\n            \n            if dir == \"right\":\n                for i in range(len(matrix[0])):\n                    result.append(matrix[0][i])\n                matrix.pop(0)\n                matrix_parcour(\"bottom\", matrix)\n                \n            elif dir == \"bottom\":\n                for i in range(len(matrix)):\n                    result.append(matrix[i][-1])\n                    matrix[i].pop(-1)\n                matrix_parcour(\"left\", matrix)\n                \n            elif dir == \"left\":\n                for i in range(len(matrix[-1])):\n                    result.append(matrix[-1][-1-i])\n                matrix.pop(-1)\n                matrix_parcour(\"top\", matrix)\n                \n            elif dir == \"top\":\n                for i in range(len(matrix) - 1, -1, -1):\n                    result.append(matrix[i][0])\n                    matrix[i].pop(0)\n                matrix_parcour(\"right\", matrix)\n\n        matrix_parcour(dir, matrix)\n        return result"
        }
      ]
    }
  ]
};